// Full syllabus: Day 1 to Day 50
const syllabus = {
  "Day 1": [
    "Introduction Software Industry",
    "SDLC - Waterfall and Agile Model",
    "Explain DevOps Syllabus",
    "Introduction to API, its types, and use cases",
    "What is Frontend vs backend",
    "Stages of application development [developer/tester/db/devops teams]"
  ],
  "Day 2": [
    "Introduction to SCM tool",
    "Difference Between Centralise-VCS and Distributed-VCS",
    "Introduction to GIT",
    "Explain Lifecycle of GIT",
    "GIT CLI instalation",
    "GIT Command (work on local-repo)",
    "git init, add, commit, logs, revert, restore, status"
  ],
  "Day 3": [
    "git branch, common types of branches, checkout, diff, merge",
    "Introduction to Remote Repo (GitHub)",
    "git clone, pull, push commands",
    "git init, config, remote"
  ],
  "Day 4": [
    "GITHUB DASHBOARD",
    "Difference between Public and Private Repo",
    "How to Search Public Repos",
    "Fork and Pull Requests",
    "Authentication methods (HTTP, SSH)"
  ],
  "Day 5": [
    "Difference between Github and Gitlab",
    "Difference between CE and EE Gitlab",
    "How to merge repo branches in gitlab",
    "How to resolve conflicts",
    "Explain IDE, install visual studio code, Auto Git",
    "Revision Session(ONLY SATURDAY) - Recap of all key concepts of GIT, GITHUB, GITLAB"
  ],
  "Day 6": [
    "Difference between Monolithic and MicroServices",
    "Difference between Traditional, Virtualization, and Containerization Deployment",
    "Intriduction to Containerization, Container, Image",
    "Introduction to Docker",
    "Difference between Docker CE and Docker EE",
    "Install Docker engine",
    "Run first container"
  ],
  // … Continue the same for all days up to Day 50
  "Day 50": [
    "EXAM(ONLY SATURDAY)"
  ]
};

// Populate day dropdown on page load
window.addEventListener('DOMContentLoaded', () => {
  const daySelect = document.getElementById('day');
  Object.keys(syllabus).forEach(day => {
    const option = document.createElement('option');
    option.value = day;
    option.text = day;
    daySelect.appendChild(option);
  });
});

// Populate topics checkboxes based on selected day
function populateTopics() {
  const day = document.getElementById('day').value;
  const topicsDiv = document.getElementById('topics');
  topicsDiv.innerHTML = ''; // Clear previous topics
  document.getElementById('output').style.display = 'none'; // Hide previous card

  if (day && syllabus[day]) {
    syllabus[day].forEach((topic, i) => {
      const checkbox = document.createElement('input');
      checkbox.type = 'checkbox';
      checkbox.id = `topic${i}`;
      checkbox.value = topic;

      const label = document.createElement('label');
      label.htmlFor = `topic${i}`;
      label.innerText = topic;

      topicsDiv.appendChild(checkbox);
      topicsDiv.appendChild(label);
      topicsDiv.appendChild(document.createElement('br'));
    });
  }
}

// Generate the training update card
function generateUpdate() {
  const trainer = "Abhipray Dhoble";
  const batch = "OnCDEC-b29";
  const mode = "Online";
  const date = new Date().toISOString().split('T')[0];
  const day = document.getElementById('day').value;

  if (!day) {
    alert("Please select a day");
    return;
  }

  const module = day;

  // Get selected topics
  const topics = [];
  document.querySelectorAll('input[type="checkbox"]:checked').forEach(cb => topics.push(cb.value));

  if (topics.length === 0) {
    alert("Select at least one topic");
    return;
  }

  const html = `
    <h1>📚 CDEC Training Update</h1>
    <p>📅 <strong>Training date:</strong> ${date}</p>
    <p>👨‍🏫 <strong>Instructor name:</strong> ${trainer}</p>
    <p>👥 <strong>Batch name:</strong> ${batch}</p>
    <p>💻 <strong>Training mode:</strong> ${mode}</p>
    <p>📖 <strong>Course module:</strong> ${module}</p>
    <p>📑 <strong>Module section:</strong> ${day}</p>
    <p>✅ <strong>Attendance:</strong> 19/30 students</p>

    <h3>📋 Topics Covered:</h3>
    <ul>
      ${topics.map(t => `<li>${t}</li>`).join('')}
    </ul>

    <footer>_Generated by CDEC Training Management System_</footer>
  `;

  const outputDiv = document.getElementById('output');
  outputDiv.innerHTML = html;
  outputDiv.style.display = 'block';
}
